# Generated by Django 6.0.3 on 2026-03-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_brand_description_ru_brand_description_uz_and_more'),
        ('categories', '0004_category_description_ru_category_description_uz_and_more'),
        ('products', '0002_alter_product_slug_alter_producttag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country_of_origin_ru',
            field=models.CharField(db_index=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin_uz',
            field=models.CharField(db_index=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producttag',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producttag',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['country_of_origin_ru'], name='products_pr_country_a90f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['country_of_origin_uz'], name='products_pr_country_e209fc_idx'),
        ),
    ]
