# Generated by Django 6.0.3 on 2026-03-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_country_of_origin_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
