# Generated by Django 6.0.3 on 2026-03-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
